<?php


namespace vnukga\migrationGenerator\helpers;

use yii\helpers\Inflector;

class GiiHelper extends BaseHelper
{
    /**
     * Namespace for models, that will be created by using Gii.
     * @var string $modelNamespace
     */
    public $modelNamespace;

    /**
     * If 1, Yii::t() will be used for generated model's labels.
     * @var int $enableI18N
     */
    public $enableI18N;

    /**
     * Base Model's class for models, generated by Gii.
     * @var string $modelBaseClass
     */
    public $modelBaseClass;

    /**
     * Category for Yii::t() (if $enableI18N is set to 1)
     * @var string $messageCategory
     */
    public $messageCategory;

    /**
     * Namespace for CRUD controllers, generated by Gii.
     * @var string $controllerNamespace
     */
    public $controllerNamespace;

    /**
     * Base Controller's class for controllers, generated by Gii.
     * @var string $baseControllerClass
     */
    public $baseControllerClass;

    /**
     * Path for generating view's files via Gii.
     * @var string $baseViewPath
     */
    public $baseViewPath;

    /**
     * Generates models and CRUD from diff's array.
     * @param array $values
     */
    public function generate(array $values)
    {
        foreach ($values['new_tables'] as $table_name => $table){
            $this->generateModel($table_name);
            $this->generateCrud($table_name);
        }
    }

    /**
     * Generates model named $table_name.
     * @param string $table_name
     */
    private function generateModel(string $table_name)
    {
        $modelClass = Inflector::id2camel($table_name, '_');
        $command = 'yii gii/model --tableName=' . $table_name
            . ' --modelClass=' . $modelClass .
            ' --ns=' . $this->modelNamespace .
            ' --enableI18N=' . $this->enableI18N .
            ' --messageCategory=' . $this->messageCategory .
            ' --baseClass=' . $this->modelBaseClass . ' interactive=0';
        $this->applyConsoleCommand($command);
    }

    /**
     * Generates CRUD for $table_name table.
     * @param string $table_name
     */
    private function generateCrud(string $table_name){
        $modelName = Inflector::id2camel($table_name, '_');
        $modelClass = $this->modelNamespace . '\\' . $modelName;
        $controllerName = $modelName . 'Controller';
        $command = 'yii gii/crud' .
            ' --modelClass=' . $modelClass .
            ' --searchModelClass=' . $modelClass . 'Seacrh' .
            ' --baseControllerClass=' . $this->baseControllerClass .
            ' --controllerClass=' . $this->controllerNamespace . '\\' . $controllerName .
            ' --viewPath=' . $this->baseViewPath . DIRECTORY_SEPARATOR . Inflector::camel2id($modelName) .
            ' --enableI18N=' . $this->enableI18N .
            ' --messageCategory=' . $this->messageCategory .
            ' interactive=0';
        $this->applyConsoleCommand($command);
    }
}